### PR TITLE
frontend/fix: #204 Added Clickable Links to Notification Cards

### PR DESCRIPTION
**Pull request by VD321**
## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
Added Clickable Links to Notification cards in driver app.

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

### CODE REVIEW

**Comment by Vignesh-772** [comment]
@VD321 attach Output.

**Comment by VD321** [comment]
Output:
[https://drive.google.com/file/d/1UgjymNY9NXCR6SihYJjfiVuzQ-ExjZXd/view?usp=sharing](url)

**Comment by VD321** [comment]
Here is the output:
[](https://drive.google.com/file/d/1UgjymNY9NXCR6SihYJjfiVuzQ-ExjZXd/view?usp=sharing)

**Comment by VD321** [comment]
Here is the output:
[Output](https://drive.google.com/file/d/1UgjymNY9NXCR6SihYJjfiVuzQ-ExjZXd/view?usp=sharing)

**Review by witcher-shailesh — APPROVED** [review]

**Pull request merged**
