### PR TITLE
updated readme to have valid GHCup url

### PR DESCRIPTION
**Pull request by wololowarrior**
## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

Updating couple of invalid url in the backend readme. There was an extra https added to the GHCup url.

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

Fixing a readme issue

## How did you test it?

No need for testing as its Readme.

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

### CODE REVIEW

**Review by srid — COMMENTED** [review]
We are switching from GHCup/Stack to Nix this week. See https://github.com/nammayatri/nammayatri/issues/356 and https://github.com/nammayatri/nammayatri/pull/361

**Comment by wololowarrior** [comment]
@srid got it

**Comment by wololowarrior** [comment]
@srid how can I start contributing to namma yatri? For starters, I've started learning Haskell. I'm primarily a python/Go dev.
But I'm struggling to identify issues to work on.

**Comment by srid** [comment]
@wololowarrior Let's move the discussion here so others can respond as well: https://github.com/orgs/nammayatri/discussions/453

**Pull request closed without merging**
